(()=>{
'use strict';
const NAMES=['MCMC / Metropolis','Diffusion','Curl Flow','Harmonic','Vortex','Shockwave','Shatter','Phyllotaxis','Wipe','Melt','Wind Blow','Chladni Nodal Set','N-Body Swarm','Lattice Quantize','Double Helix','Beam Up','Fibonacci Sphere','Tornado'];
const DESCRIPTIONS=['Muestreo probabilístico hacia superficies procedurales.','Difusión DDPM: objeto a nube de ruido.','Flujo de partículas semejante al humo.','Superficie de armónicos esféricos.','Remolino hacia un disco giratorio.','Onda expansiva con frente gaussiano.','Fragmentación en celdas rígidas.','Espiral de Fermat y ángulo áureo.','Disolución estratificada direccional.','Los splats se transforman en filamentos.','Viento, ráfagas y turbulencia.','Proyección sobre superficies nodales 3D.','Enjambre con cuatro atractores gravitacionales.','Retícula cúbica centrada en el cuerpo.','Doble hélice con conexiones.','Desmaterialización vertical ascendente.','Esferas distribuidas mediante Fibonacci.','Embudo con vórtice de Rankine.'];
const MOTION=[['amp','Amplitud',0,3,.01],['freq','Frecuencia / bandas',0,8,.05],['turb','Turbulencia',0,1,.01],['spin','Rotación',-5,5,.05],['sizeGain','Ganancia de tamaño',0,3,.05],['fade','Desvanecimiento',0,1,.01],['glow','Resplandor',0,3,.05],['seed','Semilla',0,200,1]];
const POINTS=[['point','Tamaño de punto',0,10,.1],['pointGain','Ganancia de opacidad',0,5,.05],['pointBlend','Mezcla a puntos',0,1,.01],['falloff','Suavidad de borde',.02,3,.02],['rim','Brillo del borde',0,2,.02]];
const TIME=[['duration','Duración (s)',.15,10,.05],['dwell','Espera entre ciclos (s)',0,8,.1]];
const $=s=>document.querySelector(s), v=()=>window.__viewer;
const html=(tag,cls,markup)=>{const e=document.createElement(tag);if(cls)e.className=cls;e.innerHTML=markup;return e};
const number=i=>String(i).padStart(2,'0');
function notice(s){const e=$('#g-toast');e.textContent=s;e.classList.add('visible');clearTimeout(notice.timer);notice.timer=setTimeout(()=>e.classList.remove('visible'),4200)}
function field(group,[key,label,min,max,step]){const e=html('div','g-field',`<label for="g-${key}">${label}</label><output id="gout-${key}"></output><input id="g-${key}" type="range" min="${min}" max="${max}" step="${step}" aria-label="${label}">`);group.append(e);e.querySelector('input').addEventListener('input',evt=>{const value=Number(evt.target.value);e.querySelector('output').textContent=value.toFixed(step<.1?2:step<1?1:0);const a=v();if(!a)return;if(key==='duration'||key==='dwell'){a.transition[key]=value;a.cfg.transition[key]=value}else a.cfg.params[key]=value;});}
function sync(){const a=v();if(!a)return;const c=a.cfg,t=a.transition;$('#g-select').value=c.effectIndex;$('#g-name').textContent=NAMES[c.effectIndex];$('#g-desc').textContent=DESCRIPTIONS[c.effectIndex];$('#g-counter').textContent=number(c.effectIndex)+' / 17';$('#g-model-name').textContent=c.filename;$('#g-loop').checked=t.autoCycle;$('#g-next-auto').checked=t.advanceOnCycle;$('#g-easing').value=t.easing;$('#g-rotate').checked=!!a.camera.autoRotate;[...MOTION,...POINTS,...TIME].forEach(([k,,, ,step])=>{const value=k==='duration'||k==='dwell'?t[k]:c.params[k];const input=$('#g-'+k);if(input){input.value=value;$('#gout-'+k).textContent=Number(value).toFixed(step<.1?2:step<1?1:0)}});$('#g-tint').value='#'+c.params.tint.map(x=>Math.round(x*255).toString(16).padStart(2,'0')).join('');}
function showCode(tab){const a=v();if(!a)return;const src=a.shaders.modifier;const hooks=src.lastIndexOf('void modifySplatCenter');let out=src;if(tab==='library'){let end=src.indexOf('// ============================================================ 0.');out=src.slice(0,end>0?end:hooks)}else if(tab==='hooks'){out=src.slice(Math.max(0,hooks-220))}else{const id=a.cfg.effectIndex;const markers=[...src.matchAll(/^\/\/\s*(?:=+\s*)?(\d+)\./gm)];const m=markers.find(x=>Number(x[1])===id);const next=m&&markers.find(x=>x.index>m.index);out=m?src.slice(m.index,next?next.index:hooks):src;}$('#g-source').textContent=out;document.querySelectorAll('[data-g-tab]').forEach(el=>el.classList.toggle('active',el.dataset.gTab===tab));}
function changeEffect(i,play=true){const a=v();if(!a)return;a.cfg.effectIndex=(i+18)%18;$('#g-select').value=a.cfg.effectIndex;$('#g-name').textContent=NAMES[a.cfg.effectIndex];$('#g-desc').textContent=DESCRIPTIONS[a.cfg.effectIndex];$('#g-counter').textContent=number(a.cfg.effectIndex)+' / 17';if(play){a.transition.autoCycle=false;a.transition.reset();$('#g-loop').checked=false;a.transition.out();}if($('#g-code').classList.contains('visible'))showCode($('[data-g-tab].active')?.dataset.gTab||'effect');}
function exportPreset(){const a=v();if(!a)return;const config={app:'GSCS',version:1,effectIndex:a.cfg.effectIndex,params:a.cfg.params,transition:{duration:a.transition.duration,easing:a.transition.easing,dwell:a.transition.dwell,autoCycle:a.transition.autoCycle,advanceOnCycle:a.transition.advanceOnCycle},camera:{autoRotate:a.camera.autoRotate}};const url=URL.createObjectURL(new Blob([JSON.stringify(config,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='gscs-'+number(a.cfg.effectIndex)+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1500);notice('Configuración exportada');}
async function importPreset(file){const a=v();if(!a)return;try{const data=JSON.parse(await file.text());if(Number.isInteger(data.effectIndex)&&data.effectIndex>=0&&data.effectIndex<18)a.cfg.effectIndex=data.effectIndex;for(const k of Object.keys(a.cfg.params)){if(k==='tint'){if(Array.isArray(data.params?.tint)&&data.params.tint.length===3)a.cfg.params.tint=data.params.tint.map(x=>Math.min(1,Math.max(0,Number(x)||0)));}else if(Number.isFinite(data.params?.[k]))a.cfg.params[k]=data.params[k];}const t=data.transition||{};for(const k of ['duration','dwell'])if(Number.isFinite(t[k]))a.transition[k]=t[k];if(['linear','ease in','ease out','ease in-out'].includes(t.easing))a.transition.easing=t.easing;if(typeof t.advanceOnCycle==='boolean')a.transition.advanceOnCycle=t.advanceOnCycle;a.transition.autoCycle=!!t.autoCycle;if(Number.isFinite(data.camera?.autoRotate))a.camera.autoRotate=data.camera.autoRotate;sync();notice('Configuración importada');}catch(e){notice('No se pudo cargar el JSON');}}
function build(){
 const top=html('header','g-top','<div class="g-brand" aria-label="Dr. Brown Labs · GSCS"><img class="g-brand-logo" src="./assets/dr-brown-labs.svg" alt="Dr. Brown Labs"><span class="g-brand-name">GSCS</span></div><div class="g-right"><span class="g-micro" id="g-status">INICIANDO</span><button class="g-btn sm" id="g-toggle-code">&lt;/&gt; CÓDIGO</button><button class="g-btn sm g-mobile" id="g-toggle-panel">AJUSTES</button></div>');
 const sidebar=html('aside','', '<div class="g-intro"><div class="g-label">01 / EFECTO ACTIVO</div><h1 class="g-title" id="g-name">WIND BLOW</h1><div class="g-muted" id="g-desc"></div></div>');sidebar.id='g-panel';
 const select=html('section','g-section','<h3>EFECTO / 18 MODOS</h3><select class="g-select" id="g-select" aria-label="Elegir efecto"></select><p class="g-help">GPU SHADER / 18 EFECTOS</p>');NAMES.forEach((n,i)=>{const opt=document.createElement('option');opt.value=i;opt.textContent=number(i)+' — '+n;select.querySelector('select').add(opt);});sidebar.append(select);
 sidebar.append(html('section','g-section','<h3>MODELO GAUSSIAN</h3><div class="g-muted" id="g-model-name">bonsai01.sog</div><div style="height:10px"></div><button class="g-btn g-wide" id="g-load-model">CARGAR .SOG / .PLY</button><input id="g-model-file" type="file" accept=".sog,.ply" hidden><p class="g-help">MODELO DE EJEMPLO INCLUIDO</p>'));
 const motion=html('section','g-section','<h3>MOVIMIENTO / MATERIAL</h3>');MOTION.forEach(x=>field(motion,x));sidebar.append(motion);
 const points=html('section','g-section','<h3>PUNTOS / RENDERIZADO</h3>');POINTS.forEach(x=>field(points,x));points.append(html('div','g-row','<label for="g-tint">Color de energía</label><input id="g-tint" class="g-color" type="color" value="#d9f2ff">'));sidebar.append(points);
 const playback=html('section','g-section','<h3>TIEMPO / REPRODUCCIÓN</h3>');TIME.forEach(x=>field(playback,x));playback.append(html('div','', '<div class="g-row"><label for="g-loop">Reproducción cíclica</label><input id="g-loop" type="checkbox"></div><div class="g-row"><label for="g-next-auto">Pasar al siguiente efecto</label><input id="g-next-auto" type="checkbox"></div><div class="g-row"><label for="g-rotate">Rotación automática de cámara</label><input id="g-rotate" type="checkbox"></div><div style="height:8px"></div><h3>INTERPOLACIÓN</h3><select class="g-select" id="g-easing"><option value="ease in-out">Ease in-out</option><option value="linear">Lineal</option><option value="ease in">Ease in</option><option value="ease out">Ease out</option></select>'));sidebar.append(playback);
 sidebar.append(html('section','g-section','<h3>CONFIGURACIÓN</h3><div class="g-two"><button class="g-btn" id="g-export">EXPORTAR JSON</button><button class="g-btn" id="g-import">IMPORTAR JSON</button></div><input type="file" id="g-preset-file" accept=".json" hidden><p class="g-help">18 SHADERS / PLAYCANVAS / WEBGL2</p>'));
 const transport=html('footer','', '<div class="g-transport-buttons"><button class="g-btn" id="g-prev" title="Anterior">‹</button><button class="g-btn primary" id="g-play" title="Reproducir">▶</button><button class="g-btn" id="g-reset" title="Reiniciar">↺</button><button class="g-btn" id="g-next" title="Siguiente">›</button></div><div class="g-timeline"><div class="g-timeline-head"><span id="g-state">CARGANDO</span><span id="g-progress-label">0%</span></div><input id="g-progress" type="range" min="0" max="1" step="0.001" value="0" aria-label="Progreso"></div><div class="g-counter" id="g-counter">10 / 17</div>');transport.id='g-transport';
 const code=html('aside','', '<div class="g-code-header"><div class="g-label">SHADER SOURCE / GLSL</div><button class="g-btn sm" id="g-close-code">CERRAR ×</button></div><div class="g-tabs"><button class="active" data-g-tab="effect">Effect</button><button data-g-tab="hooks">Hooks</button><button data-g-tab="library">Library</button></div><pre id="g-source"></pre>');code.id='g-code';
 const toast=html('div','', '');toast.id='g-toast';toast.setAttribute('role','status');toast.setAttribute('aria-live','polite');document.body.append(top,sidebar,transport,code,toast);
 $('#g-select').addEventListener('change',e=>changeEffect(Number(e.target.value)));
 $('#g-toggle-panel').addEventListener('click',()=>document.body.classList.toggle('g-open'));
 $('#g-toggle-code').addEventListener('click',()=>{code.classList.toggle('visible');if(code.classList.contains('visible'))showCode('effect')});$('#g-close-code').addEventListener('click',()=>code.classList.remove('visible'));document.querySelectorAll('[data-g-tab]').forEach(e=>e.addEventListener('click',()=>showCode(e.dataset.gTab)));
 $('#g-prev').addEventListener('click',()=>changeEffect((v()?.cfg.effectIndex??0)-1));$('#g-next').addEventListener('click',()=>changeEffect((v()?.cfg.effectIndex??0)+1));
 $('#g-play').addEventListener('click',()=>v()?.transition.toggle());$('#g-reset').addEventListener('click',()=>{const a=v();if(a){a.transition.autoCycle=false;a.transition.reset();$('#g-loop').checked=false}});
 $('#g-progress').addEventListener('input',e=>{const a=v();if(a){a.transition.autoCycle=false;$('#g-loop').checked=false;a.transition.scrub(Number(e.target.value))}});
 $('#g-loop').addEventListener('change',e=>{const a=v();if(a)a.transition.autoCycle=e.target.checked});$('#g-next-auto').addEventListener('change',e=>{const a=v();if(a)a.transition.advanceOnCycle=e.target.checked});
 $('#g-rotate').addEventListener('change',e=>{const a=v();if(a)a.camera.autoRotate=e.target.checked?6:0});$('#g-easing').addEventListener('change',e=>{const a=v();if(a)a.transition.easing=e.target.value});
 $('#g-tint').addEventListener('input',e=>{const a=v();if(a)a.cfg.params.tint=[1,3,5].map(i=>parseInt(e.target.value.slice(i,i+2),16)/255)});
 $('#g-load-model').addEventListener('click',()=>$('#g-model-file').click());$('#g-model-file').addEventListener('change',async e=>{const f=e.target.files?.[0];const a=v();if(!f||!a)return;$('#g-status').textContent='CARGANDO MODELO';try{await a.loadModel(f);notice('Modelo cargado: '+f.name);$('#g-model-name').textContent=f.name;$('#g-status').textContent='ACTIVO'}catch(ex){console.error(ex);notice('Error: '+ex.message);$('#g-status').textContent='ERROR'}e.target.value=''});
 $('#g-export').addEventListener('click',exportPreset);$('#g-import').addEventListener('click',()=>$('#g-preset-file').click());$('#g-preset-file').addEventListener('change',async e=>{if(e.target.files?.[0])await importPreset(e.target.files[0]);e.target.value=''});
}
function ready(){const a=v();if(!a)return;a.transition.onAdvance=()=>changeEffect(a.cfg.effectIndex+1,false);sync();$('#g-status').textContent='WEBGL2 / ACTIVO';notice('18 efectos disponibles')}
document.addEventListener('gscs-ready',ready);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
(function tick(){const a=v();if(a){const slider=$('#g-progress');if(slider&&document.activeElement!==slider)slider.value=a.transition.raw;const label=$('#g-progress-label');if(label)label.textContent=Math.round(a.transition.progress*100)+'%';const state=$('#g-state');if(state)state.textContent=({in:'RECONSTRUYENDO',out:'DISPERSANDO',held:'MANUAL',assembled:'ENSAMBLADO',dispersed:'DISPERSO'})[a.transition.state]||'ACTIVO'}requestAnimationFrame(tick)})();
})();